
name: Deoploy Website

# Controls when the action will run. 
on:
  push:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install Nodejs
        uses: actions/setup-node@v2-beta
        with:
          node-version:  14
      - name: install Surge
        run: npm install -g surge
      - name: Run Surge
        run: surge ./ panacloud-bootcamp-2020_setup_bashiruddin.surge.sh --token ${{ secrets.SURGE_TOKEN}}

      
